#if UNITY_IOS
using System.IO;
using UnityEditor.iOS.Xcode;

namespace GameFrameX.Xcode.Editor
{
    internal partial class PostProcessBuildHelper
    {
        private const string SwiftBridgingHeaderName = "Unity-iPhone-Bridging-Header.h";
        private const string SwiftBridgingFileName = "gameframex_swift_bridging.swift";

        private static void SetupSwiftBridging(PBXProject proj, string mainTargetGuid, string frameworkTargetGuid, string path, bool enabled)
        {
            if (!enabled) return;

            var swiftFile = Path.Combine(path, SwiftBridgingFileName);
            if (!File.Exists(swiftFile))
            {
                File.WriteAllText(swiftFile,
                    "// GameFrameX Swift Bridging File\n" +
                    "// GameFrameX Swift 桥接文件\n" +
                    "// Auto-generated by GameFrameX Xcode Config — DO NOT EDIT\n" +
                    "\n" +
                    "import Foundation\n");
            }

            var bridgingHeaderFile = Path.Combine(path, SwiftBridgingHeaderName);
            if (!File.Exists(bridgingHeaderFile))
            {
                File.WriteAllText(bridgingHeaderFile,
                    "// GameFrameX Swift Bridging Header\n" +
                    "// GameFrameX Swift 桥接头文件\n" +
                    "// Auto-generated by GameFrameX Xcode Config — DO NOT EDIT\n" +
                    "\n");
            }

            proj.AddFileToBuild(mainTargetGuid, proj.AddFile(swiftFile, SwiftBridgingFileName, PBXSourceTree.Source));
            proj.AddFile(bridgingHeaderFile, SwiftBridgingHeaderName, PBXSourceTree.Source);

            proj.SetBuildProperty(mainTargetGuid, "SWIFT_VERSION", "5.0");
            proj.SetBuildProperty(mainTargetGuid, "SWIFT_OBJC_BRIDGING_HEADER", SwiftBridgingHeaderName);

            proj.SetBuildProperty(frameworkTargetGuid, "SWIFT_VERSION", "5.0");

            LogHelper.Log("[SwiftBridging] Swift bridging header configured");
        }
    }
}
#endif
